docRoot                   $VH_ROOT/html/
enableGzip                1

errorlog $VH_ROOT/logs/error.log {
  useServer               1
  logLevel                DEBUG
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  rollingSize             10M
  keepDays                30
  compressArchive         0
}

index  {
  useServer               0
  indexFiles              index.html
  autoIndex               0
  autoIndexURI            /_autoindex/default.php
}

errorpage 404 {
  url                     /error404.html
}

expires  {
  enableExpires           1
}

accessControl  {
  allow                   *
}

realm SampleProtectedArea {

  userDB  {
    location              conf/vhosts/$VH_NAME/htpasswd
    maxCacheSize          200
    cacheTimeout          60
  }

  groupDB  {
    location              conf/vhosts/$VH_NAME/htgroup
    maxCacheSize          200
    cacheTimeout          60
  }
}

context /docs/ {
  location                $SERVER_ROOT/docs/
  allowBrowse             1
}

context /protected/ {
  location                protected/
  allowBrowse             1
  realm                   SampleProtectedArea
  authName                Protected
  required                user test

  accessControl  {
    allow                 *
  }
}

context /blocked/ {
  allowBrowse             0
}

context /cgi-bin/ {
  type                    cgi
  location                $VH_ROOT/cgi-bin/
}

context /phpmyadmin {
  location                /usr/local/lsws/Example/html/phpmyadmin
  allowBrowse             1
  indexFiles              index.php

  accessControl  {
    allow                 *
  }
  addDefaultCharset       off
}

context /webmail {
  location                /usr/local/lsws/Example/html/webmail
  allowBrowse             1
  indexFiles              index.php

  accessControl  {
    allow                 *
  }
  addDefaultCharset       off
}



context / {
  type                    proxy
  handler                 panel
  addDefaultCharset       off
}

rewrite  {
  enable                  0
  logLevel                0
}

vhssl  {
  keyFile                 /etc/letsencrypt/live/chandpurtelecom.xyz/privkey.pem
  certFile                /etc/letsencrypt/live/chandpurtelecom.xyz/fullchain.pem
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling          1
  ocspRespMaxAge          86400
}

context /olsapp {
  location                /usr/local/lsws/Example/html/olsapp
  allowBrowse             1
  indexFiles              index.php
  rewrite  {
        enable               1
        
        RewriteRule ^.*\.php$ - [H=application/x-httpd-panelext]
    }
  phpIniOverride {
    php_admin_value disable_functions ""
  }
  accessControl  {
    allow                 *
  }
  addDefaultCharset       off
}

extprocessor panelext {
  type                    lsapi
  address                 uds://tmp/lshttpd/panelext.sock
  maxConns                10
  env                     LSAPI_CHILDREN=10
  initTimeout             60
  retryTimeout            0
  persistConn             1
  pcKeepAliveTimeout      1
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp81/bin/lsphp
  extUser                 olspanel
  extGroup                olspanel
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           400
  procHardLimit           500
}

scripthandler  {
  add                     lsapi:panelext panelext
}
